export const HOROSCOPE_ADD = "HOROSCOPE_ADD";
export const HOROSCOPE_ADD_ERROR = "HOROSCOPE_ADD_ERROR";
export const HOROSCOPE_GET = "HOROSCOPE_GET";
export const HOROSCOPE_GET_ERROR = "HOROSCOPE_GET_ERROR";
