export const REGISTER = " REGISTER";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGIN_USER_GOOGLE = "LOGIN_USER_GOOGLE";
export const LOGIN_USER_ERROR_GOOGLE = "LOGIN_USER_ERROR_GOOGLE";

export const LOGOUT_USER = "LOGOUT_USER";

export const ISAUTHENTICATE = "ISAUTHENTICATE";

export const USER_UPDATE = "USER_UPDATE";

export const RECOVER_PASS = "RECOVER_PASS";
export const RECOVER_PASS_ERROR = "RECOVER_PASS_ERROR";

export const GET_MYACCOUT = "GET_MYACCOUT";
export const GET_MYACCOUT_ERROR = "GET_MYACCOUT_ERROR";
